#!/usr/bin/ruby

require 'rubygems'
require 'pivotal-tracker'

PivotalTracker::Client.token='aed84c37874d7e3da7f122922bc666f7'
project = PivotalTracker::Project.all.first

branches=`git branch`

branches.each_line do |line|
  branch = line[2..-2] 
  if branch =~ /^[0-9]+$/ 
    story = project.stories.find(branch)
    puts "#{line.rstrip} [#{story.current_state}] #{story.name} (#{story.url})" 
  else 
    puts line.rstrip 
  end
end
